dist: focal
sudo: false
language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"
#  - "3.10"

env:
  - SKIP_IPV6_TESTS=true

#before_install:
#  - chmod +x $TRAVIS_BUILD_DIR/tests/3proxy/bin/linux/3proxy

install:
  - python -m pip install --upgrade pip setuptools
  - pip install -r requirements-dev.txt -U
  - pip install -e .

script:
  - flake8 httpx_socks tests
  - pytest --cov=./httpx_socks tests/ -s
#  - pytest --cov=./httpx_socks tests/ --cov-report term-missing -s

after_success:
  - coveralls

#cache:
#  directories:
#    - $HOME/.cache/pip

cache: false

notifications:
  email: false
